### ISSUE TITLE
"Will you attend?" links in event mail opens incorrect urls

### ISSUE THREAD

**Issue by piavgh** [OpenPaaS-Suite/esn-frontend-calendar#120]
![Screenshot2](https://user-images.githubusercontent.com/4060207/93840596-22bb3700-fcbb-11ea-898b-84ad9e16cb28.png)

They should open the new `/excal` SPA URLs:

`http://localhost:8080/calendar/api/calendars/event/participation` => `http://localhost:9900/excal`

For example:

Instead of

```
http://localhost:8080/calendar/api/calendars/event/participation?jwt=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRlbmRlZUVtYWlsIjoidXNlcjFAb3Blbi1wYWFzLm9yZyIsIm9yZ2FuaXplckVtYWlsIjoiYWRtaW5Ab3Blbi1wYWFzLm9yZyIsInVpZCI6ImExZWM2MTUzLWM0Y2QtNGZkNS05NmUwLWYzMzYxZjAzNjI1NCIsImNhbGVuZGFyVVJJIjoiNWY1ZWRmZGViYzU0ZDQyYTE1ZWIzOGY2IiwiYWN0aW9uIjoiQUNDRVBURUQiLCJpYXQiOjE2MDA3NDI3NzR9.VSejpkyAE5RblsselFbHJp61Be55gEyu_VMv5vbQVkpi8NcGp9vtX6l27HkD6fSFUy_rnWfymD2KWhQwNC3bsWM-Kxs89ZNsTwuuvEaRokL1p6xpUcVrThU4gH8OPhGAN2seIwdnvTRboLrJZd5IT6IzOHChCtXRUrri1FNHytz8eUXByAh8idgAquBDTfiFopDJfDCRbffLxDn0xwva3_GyrjP_nBzzAdCVVKdfXOksrGGysUYyEDkH-R7dTPneWBVfJLgK4lFfNgsj32U3ir-IAK6U2QaQOrcjaQq06gEwQPEnkTMOu3c6NKwTyimALKPhZPi0r0cXJ6NbyzweDg
```

It should be:

```
http://localhost:9900/excal?jwt=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRlbmRlZUVtYWlsIjoidXNlcjFAb3Blbi1wYWFzLm9yZyIsIm9yZ2FuaXplckVtYWlsIjoiYWRtaW5Ab3Blbi1wYWFzLm9yZyIsInVpZCI6ImExZWM2MTUzLWM0Y2QtNGZkNS05NmUwLWYzMzYxZjAzNjI1NCIsImNhbGVuZGFyVVJJIjoiNWY1ZWRmZGViYzU0ZDQyYTE1ZWIzOGY2IiwiYWN0aW9uIjoiQUNDRVBURUQiLCJpYXQiOjE2MDA3NDI3NzR9.VSejpkyAE5RblsselFbHJp61Be55gEyu_VMv5vbQVkpi8NcGp9vtX6l27HkD6fSFUy_rnWfymD2KWhQwNC3bsWM-Kxs89ZNsTwuuvEaRokL1p6xpUcVrThU4gH8OPhGAN2seIwdnvTRboLrJZd5IT6IzOHChCtXRUrri1FNHytz8eUXByAh8idgAquBDTfiFopDJfDCRbffLxDn0xwva3_GyrjP_nBzzAdCVVKdfXOksrGGysUYyEDkH-R7dTPneWBVfJLgK4lFfNgsj32U3ir-IAK6U2QaQOrcjaQq06gEwQPEnkTMOu3c6NKwTyimALKPhZPi0r0cXJ6NbyzweDg
```

**Comment by asmaNode** [comment]
@piavgh the template of this email is it developed in backend side ?

**Comment by piavgh** [comment]
@asmaNode : yes, I think so

**Comment by tuanlc** [comment]
> @piavgh the template of this email is it developed in backend side ?

I confirm yes. It is built from calendar backend

**Comment by asmaNode** [comment]
https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/676

**Comment by huy-ta** [comment]
Hello @asmaNode,

There are still a few more things you need to do to resolve this issue completely:

- [ ] Confirm that it works on https://dev.open-paas.org (you will need this to be resolved first: https://github.com/OpenPaaS-Suite/esn-frontend-calendar-public/issues/19)
- [ ] After that, backport the changes to `release-1.8.x`
- [ ] After the backport has been deployed to https://openpaas.linagora.com, confirm everything works fine on https://openpaas.linagora.com

I know it's quite time-consuming but we need to go through this process carefully to make sure our users benefit from the changes.

**Comment by huy-ta** [comment]
@asmaNode I think we should not move this to "QA:Testing" until the EXCAL app works properly so that the QA team can test the whole workflow. We can keep it in "In Progress" for now.

**Comment by asmaNode** [comment]
this fix make some update on the behaviour of actions (yes , maybe , not ) in invitation ,

```js  
function generateActionLink(baseUrl, jwtPayload, action) {
    const payload = {};

    extend(true, payload, jwtPayload, { action });

    return new Promise((resolve, reject) => {
      jwt.generateWebToken(payload, (err, token) => {
        if (err) {
          return reject(err);
        }

        resolve(urlJoin(baseUrl + '/excal', '?jwt=' + token));
      });
    });
  } 
```
This is the fix to redirect action to excal app 
==>PROBLEM : the links in actions will always have /excal in base path so we have a bad request in EXCAL app

**Comment by asmaNode** [comment]
# Definition of Done

## Done
- Fixed the wrongs urls in each action button in invitation email with adding EXCAL path

**Comment by hantt12** [comment]
![2020-10-19_11-13](https://user-images.githubusercontent.com/53081477/96400959-55921580-11fc-11eb-9f5f-7abff3bc00c9.png)
After clicking on the link, blank page is shown

**Comment by huy-ta** [comment]
> ![2020-10-19_11-13](https://user-images.githubusercontent.com/53081477/96400959-55921580-11fc-11eb-9f5f-7abff3bc00c9.png)
> After clicking on the link, blank page is shown

It should be fixed via https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/224.

**Comment by hantt12** [comment]
![2020-11-03_13-44](https://user-images.githubusercontent.com/53081477/97956249-c2033c00-1dda-11eb-9898-75de94903229.png)
No @huy-ta blank page is still shown

**Comment by huy-ta** [comment]
I've checked, this won't be fixed until https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/686 is merged.

**Comment by huy-ta** [comment]
Closed in favour of https://github.com/OpenPaaS-Suite/esn-frontend-calendar-public/issues/20.
