### ISSUE TITLE
[WIP] We have another issue, which is that when looking at the detached occurrence email that I received when I'm invited by a gsuite or o365 user, the blue bar does not display information.

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#205]
We have another issue, which is that when looking at the detached occurrence email that I received when I'm invited by a gsuite or o365 user, the blue bar does not display information.

**Comment by rezk2ll** [comment]
I cannot reproduce it.

**gmail**
![image](https://user-images.githubusercontent.com/6764881/99504619-103e4080-2980-11eb-82e5-434cd8c76057.png)

**outlook**
![image](https://user-images.githubusercontent.com/6764881/99504663-1f24f300-2980-11eb-85fb-8dd588f37794.png)

**Comment by huy-ta** [comment]
I've managed to reproduce this issue with a recurrence exception email from Google Calendar:

![image](https://user-images.githubusercontent.com/24670327/104146033-d6c40780-53fb-11eb-92e2-5e12f6e6b11d.png)

**Comment by huy-ta** [comment]
This seems to be a Sabre-related issue. When the bluebar tries to get event from Sabre, Sabre returns only the master event, not the recurrence exception, so the bluebar is not able to display the information correctly.

**Comment by huy-ta** [comment]
This should be fixed via https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/261.

**Comment by hantt12** [comment]
This still happens in dev platform today as I test with Office 365 @huy-ta
