### ISSUE TITLE
When deleting a recurrence exception, the notification email doesn't show the correct event

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#220]
#### Steps to reproduce

- As **User A**:

1. Login and go to Calendar
2. Create a new event with title "Daily event", with **User B** as an attendee
3. Make one of the recurrences an exception by changing its title to "[Exception 1] Daily event", and then delete it

- As **User B**:

1. Login and to go Inbox
2. Check the event invitation/notification emails

#### Current behaviour

The last event notification email is about "Daily event" being cancelled.

#### Expected behaviour

The last event notification email should be about the recurrence exception "[Exception 1] Daily event" being cancelled, not the master event - "Daily event".

**Comment by huy-ta** [comment]
This should be fixed via https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/merge_requests/261.

**Comment by hantt12** [comment]
@huy-ta can you check this again? This still happens on Dev as I check today
